### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [VickaMarkina/kinozal#1]
1)
это две разные секции, что они делают в одном теге?
![image](https://user-images.githubusercontent.com/8464662/129564630-a21a3ca7-2462-4dc0-a6e7-62e2d93fe1cd.png)

2)
поля не должны разрываться
![image](https://user-images.githubusercontent.com/8464662/129564859-2075a6fb-fb77-45a6-aaca-321af20ab849.png)

**Comment by VickaMarkina** [comment]
https://github.com/VickaMarkina/kinozal
https://vickamarkina.github.io/kinozal/

**Comment by Alecto** [comment]
search пишется не так, как вы написали.
![image](https://user-images.githubusercontent.com/8464662/129624061-3dfb266d-978b-4a34-a796-8917ed230fbc.png)
какое отношение searsh-login здесь поиск имеет к логину?

**Comment by VickaMarkina** [comment]
https://vickamarkina.github.io/kinozal/
https://github.com/VickaMarkina/kinozal

**Comment by Alecto** [comment]
Теперь отлично, больше ошибок и замечаний нет.
Работа принята.

вт, 17 авг. 2021 г. в 16:19, VickaMarkina ***@***.***>:
